# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:latest
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
      - https_proxy=http://127.0.0.1:7897
      - http_proxy=http://127.0.0.1:7897
      - all_proxy=socks5://127.0.0.1:7897
    network_mode: "host"
